/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import modelo.Agenda;
import modelo.Contacto;

/**
 *
 * @author PC
 */
public class Busqueda extends javax.swing.JDialog {

    /**
     * Creates new form Busqueda
     */
    private Agenda agenda;
    private ArrayList<Contacto> contactos;
    
    public Busqueda(java.awt.Frame parent, boolean modal,Agenda a) {
        super(parent, modal);
        initComponents();
        agenda = a;
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfFiltro = new javax.swing.JTextField();
        bBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaResultado = new javax.swing.JList();
        lNombre = new javax.swing.JLabel();
        lTipo = new javax.swing.JLabel();
        lTelefono = new javax.swing.JLabel();
        lFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Busqueda");

        jLabel1.setText("Buscar");

        tfFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFiltroActionPerformed(evt);
            }
        });

        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        listaResultado.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaResultadoValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaResultado);

        lNombre.setText("Nombre:");

        lTipo.setText("Tipo:");

        lTelefono.setText("Telefono:");

        lFecha.setText("Fecha creacion:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lFecha)
                    .addComponent(lTelefono)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(bBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lTipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lTipo)
                .addGap(18, 18, 18)
                .addComponent(lTelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lFecha)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        // TODO add your handling code here:
        buscar();
    }//GEN-LAST:event_bBuscarActionPerformed

    private void tfFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFiltroActionPerformed
        // TODO add your handling code here:
        buscar();
    }//GEN-LAST:event_tfFiltroActionPerformed

    private void listaResultadoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaResultadoValueChanged
        // TODO add your handling code here:
        detalles();
    }//GEN-LAST:event_listaResultadoValueChanged

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lFecha;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lTelefono;
    private javax.swing.JLabel lTipo;
    private javax.swing.JList listaResultado;
    private javax.swing.JTextField tfFiltro;
    // End of variables declaration//GEN-END:variables

    private void buscar() {
        String filtro = tfFiltro.getText();
        contactos = agenda.buscar(filtro);
        ArrayList<String> listado = new ArrayList();
        for(Contacto c:contactos){
            listado.add(formatear(c));
        }
        listaResultado.setListData(listado.toArray());
    }

    private String formatear(Contacto c) {
        return c.getNombre() + " (" + c.getTelefono() + ")";
    }

    private void detalles() {
        int pos = listaResultado.getSelectedIndex();
        if(pos!=-1){
            Contacto c = contactos.get(pos);
            cargarDetalles(c);
        }else{
            cargarDetalles(null);
        }
    }

    private void cargarDetalles(Contacto c) {
        if(c!=null){
            lNombre.setText("Nombre: " + c.getNombre());
            lTipo.setText("Tipo: " + c.getTipo().getNombre());
            lTelefono.setText("Telefono: " + c.getTelefono());
            String fecha = new SimpleDateFormat("dd/MM/yyyy").format(c.getFechaCreacion());
            lFecha.setText("Fecha: " +fecha);
        }else{
            lNombre.setText("Nombre: " );
            lTipo.setText("Tipo: " );
            lTelefono.setText("Telefono: " );
            lFecha.setText("Fecha: " );
        }
    }
}
