/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import modelo.Conexion;
import modelo.Fachada;
import modelo.UsuarioAgenda;

/**
 *
 * @author PC
 */
public class MenuAgenda extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    private Conexion conexion;
    
    public MenuAgenda(Conexion c) {
        initComponents();
        conexion = c;
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemNuevoContacto = new javax.swing.JMenuItem();
        menu2 = new javax.swing.JMenu();
        itemBuscarContactos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MENU AGENDA");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jMenu1.setText("Nuevo");

        itemNuevoContacto.setText("Contacto");
        itemNuevoContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNuevoContactoActionPerformed(evt);
            }
        });
        jMenu1.add(itemNuevoContacto);

        jMenuBar1.add(jMenu1);

        menu2.setText("Buscar");

        itemBuscarContactos.setText("Contactos");
        itemBuscarContactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarContactosActionPerformed(evt);
            }
        });
        menu2.add(itemBuscarContactos);

        jMenuBar1.add(menu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 134, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemNuevoContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNuevoContactoActionPerformed
        // TODO add your handling code here:
        new CrearContacto(this, false, conexion.getUsuario()).setVisible(true);
    }//GEN-LAST:event_itemNuevoContactoActionPerformed

    private void itemBuscarContactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarContactosActionPerformed
        // TODO add your handling code here:
        new Busqueda(this,false,conexion.getUsuario().getAgenda()).setVisible(true);
    }//GEN-LAST:event_itemBuscarContactosActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Fachada.getInstancia().logout(conexion);
    }//GEN-LAST:event_formWindowClosing

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemBuscarContactos;
    private javax.swing.JMenuItem itemNuevoContacto;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menu2;
    // End of variables declaration//GEN-END:variables
}
